# Numppy Assignment
* Easy

In [194]:
import numpy as np
import time

In [12]:
# 1. Create a 1D array of 20 sequential integers and reshape it into a 4x5 matrix.
arr = np.random.randint(100, size=(20))

newarr = arr.reshape(4, 5)

print(newarr)

[[53 12 71 25 98]
 [83 73  9 34 91]
 [39 34  5 77 49]
 [75  9 49 97 40]]


In [22]:
# 2. Write the code using np.arange() to get all even numbers between 21 and 70, (70 inclusive)

arr = np.arange(22, 71, 2)

print(arr)

[22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68
 70]


In [24]:
# 3. Write the code using np.arange() to get all odd numbers between 20 and 71. (71 inclusive)

arr = np.arange(21, 72, 2)

print(arr)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71]


In [26]:
# 4. Generate an array of 15 random integers and sort it in ascending order.
arr = np.random.randint(100, size=(15))
arr = np.sort(arr)

print(arr)

[16 19 23 28 29 33 48 51 62 66 67 76 77 80 82]


In [34]:
# 5. Create a 1D array of zeros of length 10 and set the 5th element to 1.
arr = np.zeros(10)
arr[4] = 1

print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [35]:
# 6. Find the unique elements in a given array [1, 2, 2, 3, 4, 4, 5].
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_arr = np.unique(arr)

print(unique_arr)

[1 2 3 4 5]


In [41]:
# 7. Create an array with values ranging from 0 to 10 and reverse the array.
arr = np.arange(0, 10)
reverse_arr = np.flip(arr)

print(reverse_arr)

[9 8 7 6 5 4 3 2 1 0]


In [81]:
# 8. Given a list of birds and their corresponding age, calculate:
    # birds = ['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'plovers', 'plovers', 'Cranes', 'spoonbills']
    # age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]
        # a. the mean age of the Crane bird (rounded off to 2 decimal points)
        # b. find the name of the oldest bird in the list

birds = np.array(['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'plovers', 'plovers', 'Cranes', 'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])

matrix = np.column_stack((birds, age))

crane_bird_age = matrix[matrix[:, 0] == 'Cranes', 1]
mean_crane_bird_age = np.mean(crane_bird_age.astype(float))

print("mean_crane_bird_age: ", mean_crane_bird_age)

oldest_age = np.min(matrix[:, 1].astype(float))
oldest_bird = matrix[matrix[:,1].astype(float)==oldest_age, 0]

print("oldest_bird: ", oldest_bird)

mean_crane_bird_age:  4.75
oldest_bird:  ['plovers']


In [111]:
# 9. Given a 2d array, write a program to return a subarray such that the subarray consists of the elements from:
    # a. the second to the fourth row of the original array,
    # b. the elements in these rows should be from the last three columns of the corresponding rows of the original array,
    # c. the rows should be in reversed order.

matrix = np.array([
                    [1, 2, 3, 4, 5],
                    [11, 12, 13, 14, 15],
                    [21, 22, 23, 24, 25],
                    [31, 32, 33, 34, 35],
                    [41, 42, 43, 44, 45]
                  ])

print("second to fourth raw:\n", matrix[2:5])
print("last tree column:\n", matrix[:, -3:])
print("rows reversed order\n", np.flip(matrix))

second to fourth raw:
 [[21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]
last tree column:
 [[ 3  4  5]
 [13 14 15]
 [23 24 25]
 [33 34 35]
 [43 44 45]]
rows reversed order
 [[45 44 43 42 41]
 [35 34 33 32 31]
 [25 24 23 22 21]
 [15 14 13 12 11]
 [ 5  4  3  2  1]]


* Moderate

In [120]:
# 1. Create a 4x4 matrix and replace all elements on its diagonal with 7.
matrix = np.random.randint(10, size=(4, 4))

print("before: \n", matrix)
np.fill_diagonal(matrix, 7)
print("after: \n", matrix)

before: 
 [[3 7 6 5]
 [5 9 6 1]
 [1 2 0 6]
 [4 7 8 5]]
after: 
 [[7 7 6 5]
 [5 7 6 1]
 [1 2 7 6]
 [4 7 8 7]]


In [127]:
# 2. Given two arrays of the same size, compute their element-wise product.

arr1 = np.random.randint(10, size=(5))
arr2 = np.random.randint(10, size=(5))

print("arr1: ", arr1)
print("arr2: ", arr2)

ans = np.multiply(arr1, arr2)
print("ans: ", ans)

arr1:  [7 8 4 1 1]
arr2:  [5 4 4 6 0]
ans:  [35 32 16  6  0]


In [135]:
# 3. Create a random 6x6 matrix and compute the mean and standard deviation of its elements.
matrix = np.random.randint(10, size=(2, 2))

mean_value = np.mean(matrix)
std_deviation = np.std(matrix)

print("matrix: \n",matrix)
print("mean_value: ",mean_value)
print("std_deviation: ",std_deviation)

matrix: 
 [[4 3]
 [8 6]]
mean_value:  5.25
std_deviation:  1.920286436967152


In [144]:
# 4. Stack two arrays vertically and horizontally (use vstack and hstack).
arr1 = np.random.randint(10, size=(5))
arr2 = np.random.randint(10, size=(5))

print("arr1: ", arr1)
print("arr2: ", arr2)

vstack = np.vstack((arr1, arr2))
print("vstack: ", hstack)
hstack = np.hstack((arr1, arr2))
print("hstack: ", hstack)

arr1:  [3 3 2 9 3]
arr2:  [1 8 9 1 1]
vstack:  [5 0 3 1 0 0 1 3 3 3]
hstack:  [3 3 2 9 3 1 8 9 1 1]


In [149]:
# 5. Create a 1D array of 50 random floats between 0 and 1, and count how many values are greater than 0.5.

arr =  np.random.rand(50)

print("arr: ", arr)
res = arr[arr[:] > 0.5]
print("\ngreater than 0.5: ", len(res))

arr:  [0.96449922 0.66622886 0.51955848 0.36001625 0.23053753 0.19137493
 0.74470322 0.83102451 0.6799818  0.80142439 0.18610255 0.06902488
 0.88809417 0.17087566 0.45640913 0.6158132  0.44652557 0.96856382
 0.08340789 0.74133049 0.01577197 0.35461413 0.51521059 0.84698261
 0.10640772 0.57476836 0.69842593 0.88336208 0.18063    0.23318074
 0.77755994 0.38182336 0.09832481 0.48802165 0.40401049 0.18238735
 0.88767074 0.85223456 0.76925051 0.93261285 0.68024348 0.27790583
 0.59739068 0.7654438  0.55910603 0.46733795 0.46966614 0.83172637
 0.06227789 0.54588758]

greater than 0.5:  27


In [162]:
# 6. Given a list of birds and their corresponding age, return the name of birds sorted according to age (ascending)
# birds = ['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'plovers', 'plovers', 'Cranes', 'spoonbills']
# age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

birds = ['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'plovers', 'plovers', 'Cranes', 'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

matrix = np.column_stack((birds, age))

print("before: \n", matrix)
matrix = matrix[matrix[:, 1].argsort()]
print("shorted: \n", matrix)

before: 
 [['spoonbills' '5.5']
 ['plovers' '6.0']
 ['plovers' '3.5']
 ['plovers' '1.5']
 ['plovers' '3.0']
 ['Cranes' '4.0']
 ['plovers' '3.5']
 ['plovers' '2.0']
 ['Cranes' '5.5']
 ['spoonbills' '6.0']]
shorted: 
 [['plovers' '1.5']
 ['plovers' '2.0']
 ['plovers' '3.0']
 ['plovers' '3.5']
 ['plovers' '3.5']
 ['Cranes' '4.0']
 ['spoonbills' '5.5']
 ['Cranes' '5.5']
 ['plovers' '6.0']
 ['spoonbills' '6.0']]


In [167]:
# 7. Given the shape of an array and a range, Return an array of specified shape, consisting of
    # random integers from "discrete uniform" distribution, in given range [low, high].
    # Note: high is inclusive in range.
    # Input Format:
        # o Input has two lines.
        # o First line contains the shape of the array.
        # o Second line contains the range (low, high).
        # Output Format: A NumPy array

shape = (3,4)
min_range = 1
max_range = 10

matrix = np.random.randint(min_range, max_range+1, size=shape)
print(matrix)

[[ 3  7  3  3]
 [ 2  1  6  5]
 [ 4  3  2 10]]


# Challenging

In [183]:
# 1. Create a 10x10 matrix with random integers and find the indices of the top 3 maximum values.
    # * Concepts: Matrix generation, indexing with conditions.

matrix = np.random.randint(100, size=(10, 10))
flat_matrix = matrix.flatten()
a = np.array([9, 4, 4, 3, 3, 9, 0, 4, 6, 0])
index = flat_matrix.argsort()[-3:]

print(index)

[81 75 12]


In [189]:
# 2. Solve a system of three linear equations using NumPy’s linalg.solve() function.
    # * Concepts: Linear algebra, system of equations.

a = np.array([[2, 3], [4, 1]])
b = np.array([5, 6])

x = np.linalg.solve(a, b)
print(x)

[1.3 0.8]


In [192]:
# 3. Generate a random 8x8 matrix and compute its eigenvalues and eigenvectors.
    # * Concepts: Linear algebra, eigenvalues/eigenvectors.
A = np.array([[4, 2], 
              [1, 3]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Output the results
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [237]:
# 4. Create a large random matrix (1000x1000) and find the time taken to compute the sum of its elements.
    # * Concepts: Performance evaluation, time computation.

# Record the start time
start_time = time.time()

matrix = np.random.randint(10, size=(1000, 1000))
matrix_sum = np.sum(matrix)

# Record the end time
end_time = time.time()

# Calculate the total run time
total_time = end_time - start_time
print(f"Total script run time: {total_time:.6f} seconds")
print("matrix: ", matrix)
print("matrix_sum: ", matrix_sum)

Total script run time: 0.020567 seconds
matrix:  [[5 7 2 ... 0 5 4]
 [8 9 5 ... 8 9 6]
 [4 7 5 ... 6 4 4]
 ...
 [5 3 4 ... 7 7 6]
 [3 4 4 ... 1 9 3]
 [2 8 3 ... 6 0 6]]
matrix_sum:  4497603


In [239]:
# 5. Implement matrix multiplication of two large matrices (500x500) without using 
    # numpy.dot() and compare the performance with NumPy's dot product.
    # * Concepts: Matrix multiplication, performance comparison.

# Record the start time
start_time = time.time()

matrix1 = np.random.randint(10, size=(500, 500))
matrix2 = np.random.randint(10, size=(500, 500))
matrix_mult = matrix1 * matrix2

# Record the end time
end_time = time.time()

# Calculate the total run time
total_time = end_time - start_time
print(f"Total script run time: {total_time:.6f} seconds")
print("matrix1: ", matrix1)
print("matrix2: ", matrix2)
print("matrix_mult: ", matrix_mult)

Total script run time: 0.010642 seconds
matrix1:  [[8 2 9 ... 3 5 2]
 [9 2 0 ... 9 7 1]
 [0 9 9 ... 6 1 4]
 ...
 [1 2 8 ... 5 2 2]
 [9 8 2 ... 6 2 0]
 [3 0 4 ... 8 8 6]]
matrix2:  [[3 0 0 ... 3 9 5]
 [3 0 2 ... 9 2 7]
 [9 0 5 ... 0 7 8]
 ...
 [7 8 9 ... 2 2 4]
 [6 7 1 ... 7 3 8]
 [5 3 0 ... 9 7 9]]
matrix_mult:  [[24  0  0 ...  9 45 10]
 [27  0  0 ... 81 14  7]
 [ 0  0 45 ...  0  7 32]
 ...
 [ 7 16 72 ... 10  4  8]
 [54 56  2 ... 42  6  0]
 [15  0  0 ... 72 56 54]]
