# 1. Array Creation
    a. numpy.array(): Create an array.
    b. numpy.zeros(): Create an array filled with zeros.
    c. numpy.ones(): Create an array filled with ones.
    d. numpy.empty(): Create an empty array (values are uninitialized).
    e. numpy.arange(): Create an array with a range of values.
    f. numpy.linspace(): Create an array with evenly spaced values over a specified interval.
    g. numpy.eye(): Create a 2D identity matrix.
    h. numpy.random.rand(): Create an array of given shape filled with random values.

In [4]:
import numpy as np

In [5]:
# a. numpy.array(): Create an array.
# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Create a 2D array
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

[1 2 3 4 5]
[[1 2]
 [3 4]]


In [6]:
# b. numpy.zeros(): Create an array filled with zeros.
# Create a 1D array of 5 zeros
arr_zeros1 = np.zeros(5)
print(arr_zeros1)

# Create a 2D array (3x3) of zeros
arr_zeros2 = np.zeros((3, 3))
print(arr_zeros2)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# c. numpy.ones(): Create an array filled with ones.
# Create a 1D array of 5 ones
arr_ones1 = np.ones(5)
print(arr_ones1)

# Create a 2D array (3x3) of ones
arr_ones2 = np.ones((3, 3))
print(arr_ones2)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# d. numpy.empty(): Create an empty array (values are uninitialized).
# Create a 1D empty array of size 5
arr_empty1 = np.empty(5)
print(arr_empty1)

# Create a 2D empty array (2x3)
arr_empty2 = np.empty((2, 3))
print(arr_empty2)

[4.67464259e-310 2.16937688e+233 2.81448649e+161 5.26757081e+170
 1.06209545e+248]
[[4.67464259e-310 0.00000000e+000 2.16937688e+233]
 [2.81448649e+161 5.26757081e+170 1.06209545e+248]]


In [10]:
# e. numpy.arange(): Create an array with a range of values.
# Create an array of values from 0 to 9
arr_range = np.arange(10)
print(arr_range)

# Create an array of values from 1 to 10, with a step of 2
arr_step_range = np.arange(1, 11, 2)
print(arr_step_range)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [11]:
# f. numpy.linspace(): Create an array with evenly spaced values over a specified interval.
# Create 5 evenly spaced values between 0 and 1
arr_linspace = np.linspace(0, 1, 5)
print(arr_linspace)

# Create 10 evenly spaced values between 1 and 10
arr_linspace2 = np.linspace(1, 10, 10)
print(arr_linspace2)

[0.   0.25 0.5  0.75 1.  ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [12]:
# g. numpy.eye(): Create a 2D identity matrix.
# Create a 3x3 identity matrix
arr_eye = np.eye(3)
print(arr_eye)

# Create a 4x4 identity matrix
arr_eye2 = np.eye(4)
print(arr_eye2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
# h. numpy.random.rand(): Create an array of given shape filled with random values.
# Create a 1D array of 5 random values
arr_rand1 = np.random.rand(5)
print(arr_rand1)

# Create a 2D array (3x3) of random values
arr_rand2 = np.random.rand(3, 3)
print(arr_rand2)

[0.90427273 0.6164078  0.05076053 0.95980928 0.98635499]
[[0.18183931 0.97283629 0.69085143]
 [0.80271946 0.4165247  0.82728961]
 [0.66957065 0.34792749 0.9215409 ]]


# 2. Array Manipulation
    a. numpy.reshape(): Change the shape of an array.
    b. numpy.flatten(): Flatten a multi-dimensional array.
    c. numpy.ravel(): Return a contiguous flattened array.
    d. numpy.transpose(): Transpose an array.
    e. numpy.swapaxes(): Interchange two axes of an array.
    f. numpy.concatenate(): Join a sequence of arrays along an existing axis.
    g. numpy.stack(): Join a sequence of arrays along a new axis.
    h. numpy.split(): Split an array into multiple sub-arrays.
    i. numpy.tile(): Construct an array by repeating an array.

In [15]:
# a. numpy.reshape(): Change the shape of an array.
# Create a 1D array and reshape it to a 2D array
arr = np.arange(12)  # 1D array [0, 1, 2, ..., 11]
reshaped_arr = np.reshape(arr, (3, 4))  # 2D array with shape (3, 4)
print(reshaped_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
# b. numpy.flatten(): Flatten a multi-dimensi# Create a 2D array
# Create a 2D array
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])

# Flatten the array into 1D
flattened_arr = arr_2d.flatten()
print(flattened_arr)

[1 2 3 4 5 6]


In [23]:
# c. numpy.ravel(): Return a contiguous flattened array.
# Create a 2D array
arr_2d = np.array([[7, 8], [9, 10]])

# Use ravel to flatten it
raveled_arr = np.ravel(arr_2d)
print(raveled_arr)

[ 7  8  9 10]


In [25]:
# d. numpy.transpose(): Transpose an array.
# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the array
transposed_arr = np.transpose(arr_2d)
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


In [27]:
# e. numpy.swapaxes(): Interchange two axes of an array.
# Create a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Swap axes (0 and 2)
swapped_arr = np.swapaxes(arr_3d, 0, 2)
print(swapped_arr)

[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


In [28]:
# f. numpy.concatenate(): Join a sequence of arrays along an existing axis.
# Create two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
concatenated_arr = np.concatenate((arr1, arr2), axis=0)
print(concatenated_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [34]:
# g. numpy.stack(): Join a sequence of arrays along a new axis.
# Create two 1D arrays
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

# Stack them along a new axis
stacked_arr = np.stack((arr1, arr2), axis=0)  # Stacks along rows
print(stacked_arr)

[[1 2]
 [3 4]]


In [35]:
# h. numpy.split(): Split an array into multiple sub-arrays.
# Create a 1D array
arr = np.arange(9)

# Split the array into 3 equal parts
split_arr = np.split(arr, 3)
print(split_arr)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [36]:
# i. numpy.tile(): Construct an array by repeating an array.
# Create a 1D array
arr = np.array([0, 1, 2])

# Repeat the array 2 times along each axis
tiled_arr = np.tile(arr, (2, 3))
print(tiled_arr)

[[0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]]


# 3. Array Operations
    a. numpy.add(): Element-wise addition.
    b. numpy.subtract(): Element-wise subtraction.
    c. numpy.multiply(): Element-wise multiplication.
    d. numpy.divide(): Element-wise division.
    e. numpy.dot(): Dot product of two arrays.
    f. numpy.matmul(): Matrix product of two arrays.
    g. numpy.power(): Element-wise exponentiation.
# 4. Statistical Functions
    a. numpy.mean(): Compute the arithmetic mean.
    b. numpy.median(): Compute the median.    a. numpy.std(): Compute the standard deviation.
    c. numpy.var(): Compute the variance.
    d. numpy.min(): Return the minimum value.
    e. numpy.max(): Return the maximum value.
    f. numpy.sum(): Sum of array elements.
    g. numpy.prod(): Product of array elements.
# 5. Linear Algebra
    a. numpy.linalg.inv(): Compute the inverse of a matrix.
    b. numpy.linalg.det(): Compute the determinant of a matrix.
    c. numpy.linalg.eig(): Compute the eigenvalues and right eigenvectors of a square array.
    d. numpy.linalg.svd(): Singular Value Decomposition.
    e. numpy.dot(): Perform dot product, essential for various mathematical computations in data science.
# 6. Fourier Transform and Signal Processing
    a. numpy.fft.fft(): Compute the one-dimensional discrete Fourier Transform.
    b. numpy.fft.ifft(): Compute the inverse of the one-dimensional discrete Fourier Transform.
# 7. Random Number Generation
    a. numpy.random.rand(): Generate uniform random numbers.
    b. numpy.random.randn(): Generate samples from the standard normal distribution.
    c. numpy.random.randint(): Generate random integers.
    d. numpy.random.choice(): Generate a random sample from a given array.
# 8. Logical Operations
    a. numpy.all(): Test whether all array elements are True.
    b. numpy.any(): Test whether any array element is True.
    c. numpy.where(): Return elements chosen from x or y depending on a condition.
# 9. File I/O
    a.  numpy.load(): Load an array from a binary file. 
    b. numpy.save(): Save an array to a binary file.
    c. numpy.loadtxt(): Load data from a text file.
    d. numpy.savetxt(): Save an array to a text file.
# 10. Broadcasting
    a. NumPy automatically handles broadcasting, allowing arithmetic operations on arrays of different shapes.
# 11. Other Utilities
    a. numpy.unique(): Find the unique elements of an array.
    b. numpy.argsort(): Returns the indices that would sort an array.
    c. numpy.meshgrid(): Create coordinate matrices from coordinate vectors.